### PR TITLE
Sort Trakt Progress by "recently watched"

### PR DESCRIPTION
**Pull request by Kr1ss-XD**
Currently it's being sorted by "recently aired", which obviously doesn't
make much sense

### CODE REVIEW

**Comment by JGuire** [comment]
I saw this change and went looking for a fix because it seemed broken.  The old sort worked good for me, but this one is slightly annoying.  The problem is not necessarily the sort type, but the fact that the ascending/descending order does not affect it.  With this sort, I would want the most recently watched at the bottom of the list.  Here's my suggestion - make the sort type selectable from 4 options: most recently watched, least recently watched, most recently aired, or least recently aired.  If you don't like all four options, at least provide the first two.

**Comment by Kr1ss-XD** [comment]
U __can__ change the sort order :D

**Comment by JGuire** [comment]
Thanks for the quick reply, Kr1ss-XD.  However, selecting ascending or descending does not actually change the order for me.  Are you saying it does work for you?

**Comment by Kr1ss-XD** [comment]
Yes. But only changing between scending or descending; other options don't have effect in Covenant.
Maybe u see no change because the progress is still in cache. Should change when u watch or unwatch an episode so that the progress list is force-reloaded.

**Comment by JGuire** [comment]
I've just tried the following:
1. Set default sorting for Watched Progress to "Recently Aired".
2. Set unwatched and then watched on an episode.

The effect was to move that show to the top of the list.  The displayed sort order did not change; it is still in "Recently Viewed" order.

Any other ideas?  (I do appreciate the help.)

**Comment by Kr1ss-XD** [comment]
Yes, _"Recently Aired"_ doesn't have effect in Covenant. 
During the tests on my end, I could only change between _"Recently Watched"_ and _"Oldest Watched"_. That's what I meant above : 
>But only changing between ascending or descending; other options don't have effect in Covenant.

Sorry if I'm expressing myself a bit unclearly; English isn't my native language 😀 

I think I gonna find out if it's possible to take over the default sort setting from the Trakt acc into Covenant via the Trakt API. Can't guarantee yet that it's possible, but will definetely look into the documentation to find out.

If that's not doable, I could at least submit a PR which adds a new setting in Covenant, so that u can decide to have the Progress sorted by either _"Recently Watched"_ (which would be the default then) or _"Oldest Watched"_, and see if the devs accept that.

**Comment by JGuire** [comment]
Just so we were both doing the exact same, I also tried setting "Oldest Watched" via the Trakt Site.  The same thing happened.  The only difference is that the show was initially placed at the bottom of the list, but the list order was not otherwise changed.  I then exited and re-entered to find it at the top of the list.  The list was still in "Recently Watched" order.

Maybe I am not understanding what you said.  How did you change between "Recently Watched" and "Oldest Watched"?  Did you mean to change it on the Trakt website or some other way? 

What you said below seems the most logical way to proceed:

> I think I gonna find out if it's possible to take over the default sort setting from the Trakt acc into Covenant via the Trakt API. Can't guarantee yet that it's possible, but will definetely look into the documentation to find out.
> 
> If that's not doable, I could at least submit a PR which adds a new setting in Covenant, so that u can decide to have the Progress sorted by either "Recently Watched" (which would be the default then) or "Oldest Watched", and see if the devs accept that.

**Comment by Kr1ss-XD** [comment]
Yep I've just changed it to _"Oldest Watched"_ on the Trakt website. Next time the Progress list was loaded in Covenant, the sort order was vice versa as it's been before (i.e. the most recently watched show was at the end of the list rather than on top). TBH, I can't explain why that doesn't seem to be working on ur side. Probably I need do some more tests to find out.

Nevertheless, I gonna do some research 2nite when I'm back at my PC and see which way we can follow here. Either : 

- use the default user setting from the web interface (if supported by the Trakt API), or at least
- add a setting to decide if sorting by _"Recently Watched"_ or _"Oldest Watched"_

Then we'll see what the devs decide about that.

**Comment by JGuire** [comment]
I have been unable to determine why the sort order works for you and not for me.  This is not surprising since it is the first time I've looked at Python code.  Hopefully, the request you are making will make the point moot.  For the time being, I have just edited my copy of the script to sort by 'premiered' as before.

**Pull request merged**
