### PR TITLE
Clean alluc, add allrls, fix directdl

### PR DESCRIPTION
**Pull request by Maston1c**
Alluc results are pretty bad a lot of times, attempted to fix it a bit.

Added and fixed other sources.

### CODE REVIEW

**Comment by Maston1c** [comment]
Anyone know why some sources are showing HD even though they are not?

Does not seem to be the provider file since it is returning "'quality': 'SD'" in the return statement.

**Comment by Colossal1** [comment]
@Maston1c - thanks for the fixes. I have merged without testing alluc again. So hope it works. The quality issue should also be fixed in the next release.

**Comment by weekendsource** [comment]
I tend to disagree with proposed alluc changes. Imho we shouldn't arbitrary filter titles,  because then we could have a situation like this one: https://imgur.com/a/Wvv4s

Alluc api give results, as a stream language, by fethching metadata from alluc api, and it's not perfect, it happens that sometimes there is some wrong info in metadata. But, it's constantly improving and this is really not a problem even now.
We could easily skip "wrong" link and there is plenty of info given (as a release name, size) to judge the link value.  It's better to have more to choose from than less. 

Proposed scraper change effectively cut many valid results. If we by all means want filtering by title I guess there to do it in sources.py module, and such behavior could be configurable in settings, not at a scraper level.

**Comment by Maston1c** [comment]
What is broken about that image? I made it check if french is not in the name of the movie before taking out the result. Almost every thing I searched for had a french link/3D link and sometimes it plays without you wanting since all the sources above it are broken and it plays automatically.

Take it out if you want, but at least leave it where it makes sure it checks for S##E## or the year otherwise it shows the complete wrong thing very often.

Samples, trailers, extras, even subtitles even show up a lot of time so I made it check.

**Comment by weekendsource** [comment]
Sorry, my bad, I wasn't really looked into your pr. Well, since it's accepted as it is I removed the filter logic into a function, so let's see how it will roll :) I'll make pr right now.

**Comment by weekendsource** [comment]
here it is https://github.com/Colossal1/script.module.covenant/pull/10 What do you think, could be the filtering function moved to something like source_utils maybe?

**Pull request merged**
