### PR TITLE
Fixed covenant hang-on-exit

### PR DESCRIPTION
**Pull request by Fordi**

### CODE REVIEW

**Comment by Fordi** [comment]
I'll note, I've only has this happen on Linux and Android.  It doesn't occur on Windows.  I suppose the impl for xbmc.sleep is different there.

**Comment by Fordi** [comment]
I see in the xbmc docs that there's an appropriate function for this, on instances of Monitor, called `waitForAbort`.  

What I implemented is quick, and circumvents the problem created by long sleeps across the module - but the better solution would be to run through your code and use the right tool for the job.

Implementor's choice, I suppose.  Merge in this quick-hack PR, or clean up the sleeps the right way.

**Comment by devilsport** [comment]
Yes, but for it to be compatible with all Kodi versions better use xbmc.abortRequested:
http://kodi.wiki/view/Service_add-ons

**Comment by Fordi** [comment]
Alright; that's what my PR does.  Based on that wiki page, you should probably pull it.

**Comment by Fordi** [comment]
I read the docs _after_ I wrote the PR; the original code is based on what was already in the python files I was looking at.

**Pull request merged**
